apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-config
  namespace: n8n
  labels:
    app: n8n
data:
  N8N_HOST: "n8n.dmarmijosa.com"
  N8N_PORT: "5678"
  N8N_PROTOCOL: "https"
  WEBHOOK_URL: "https://n8n.dmarmijosa.com/"
  GENERIC_TIMEZONE: "America/Guayaquil"  # Ajusta tu zona horaria
  N8N_LOG_LEVEL: "info"
  N8N_METRICS: "true"
  N8N_DISABLE_UI: "false"
  N8N_ENCRYPTION_KEY: "n8n-encryption-key-change-me"  # Cambia por una clave segura
