apiVersion: v1
kind: Secret
metadata:
  name: n8n-secrets
  namespace: n8n
  labels:
    app: n8n
type: Opaque
data:
  N8N_BASIC_AUTH_USER: "YWRtaW4="
  N8N_BASIC_AUTH_PASSWORD: "MTIyNTE2MTkzMA=="
  DB_PASSWORD: ""
