apiVersion: v1
kind: Service
metadata:
  name: n8n-service
  namespace: n8n
  labels:
    app: n8n
spec:
  type: NodePort
  ports:
  - port: 5678
    targetPort: 5678
    nodePort: 30678  # Puerto que usarás en nginx proxy manager
    protocol: TCP
    name: http
  selector:
    app: n8n
